### ISSUE TITLE
Error 35 on socket.read()

### ISSUE THREAD

**Issue by izqui** [AlwaysRightInstitute/SwiftSockets#10]
Hi!

First of all thanks for your work, the library is super cool. 

I have a problem with the library and it is that it randomly returns error 35 on socket.listen. The distribution of the errors seems to be arbitrary and the it happens like 1/3 of the times, I have also observed that when I'm debugging and putting breakpoints between connections, it doesn't happen. I also tried other queues different from the main queue, without success.

My current implementation is [here](https://github.com/izqui/Taylor/blob/736bf1c7743836754809f2d59b4aa1afd4aeb867/Taylor/Socket.swift#L47).

I have no clue what could be the origin of the issue. 

![screen shot 2015-10-13 at 8 25 37 pm](https://cloud.githubusercontent.com/assets/447328/10464171/aef5ef5c-71e8-11e5-83c2-10232780e480.png)

**Comment by helje5** [comment]
On 13 Oct 2015, at 20:28, Jorge Izquierdo <notifications@github.com> wrote:
> I have a problem with the library and it is that it randomly returns error 35 on socket.listen.

35 seems to be EAGAIN:

  http://src.gnu-darwin.org/src/sys/sys/errno.h.html

> The distribution of the errors seems to be arbitrary and the it happens like 1/3 of the times, I have also observed that when I'm debugging and putting breakpoints between connections, it doesn't happen.

EAGAIN happens if the socket would block on the read (no data is available), i.e. in your code:

  let (size, data, error) = socket.read()

If there is nothing to read, you’ll get EGAIN (aka try-later). It’s a non-blocking socket after all …

You can set it to blocking via 

  socket.isNonBlocking = false

but then reads() will block your whole queue. Instead rewrite your code to use the active-sockets onRead, as shown in my EchoServer sample:

  https://github.com/AlwaysRightInstitute/SwiftSockets/blob/develop/ARIEchoServer/EchoServer.swift


> I also tried other queues different from the main queue, without success.

Yeah, why would that be any different? Can’t follow you on this one.

hh

**Comment by izqui** [comment]
Ok, `socket.isNonBlocking = false` seems to have solved the problem.

When not blocking, it would give error 35 when I made the request, so there would have been data in the socket and when I ignored the data coming with error 35, that data would never be read.

**Comment by helje5** [comment]
Again,

making the accepted socket blocking is not a viable solution. You need to perform evented IO on that socket two (via onRead as shown in the Echo sample).

hh

**Comment by izqui** [comment]
Ok, thanks! It is solved now :)
